#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <baseline_current|more_conservative|profit_tighter|trend_defensive>" >&2
  exit 2
fi

PROFILE="$1"
ROOT="${LIGHTER_MM_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
LOG_ROOT="${CHALLENGER_LOG_ROOT:-$ROOT/logs/challengers}"
LOG_DIR="${LOG_DIR:-$LOG_ROOT/$PROFILE}"
CAPITAL="${CHALLENGER_CAPITAL:-500}"

mkdir -p "$LOG_DIR"

export MARKET_SYMBOL="${MARKET_SYMBOL:-BTC}"
export LIGHTER_MM_CONFIG="${LIGHTER_MM_CONFIG:-$ROOT/configs/btc_live_100.json}"
export LOG_DIR
export RESEARCH_LOG_ENABLED="${RESEARCH_LOG_ENABLED:-true}"
export RESEARCH_LOG_ROOT_DIR="${RESEARCH_LOG_ROOT_DIR:-$LOG_DIR/research}"
export RESEARCH_LOG_RAW_RETENTION_DAYS="${RESEARCH_LOG_RAW_RETENTION_DAYS:-3}"
export RESEARCH_LOG_COMPRESSED_RETENTION_DAYS="${RESEARCH_LOG_COMPRESSED_RETENTION_DAYS:-30}"
export RESEARCH_LOG_MAX_TOTAL_MB="${RESEARCH_LOG_MAX_TOTAL_MB:-1024}"
export RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS="${RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS:-3600}"
export PYTHONUNBUFFERED=1

# Keep paper challengers gentle on the live VPS. They still use the same public
# Lighter feeds and dry-run fill simulator, but are not latency-critical.
export MIN_LOOP_INTERVAL="${MIN_LOOP_INTERVAL:-0.2}"
export SANITY_CHECK_INTERVAL="${SANITY_CHECK_INTERVAL:-30}"

case "$PROFILE" in
  baseline_current)
    # Mirrors the current live config as closely as possible.
    ;;
  more_conservative)
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.12}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.9}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-10.0}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.0}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.7}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-9.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.25}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.75}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-240}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.85}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.65}"
    ;;
  profit_tighter)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.1}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-6.0}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-30.0}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-0.55}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-2.4}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-14.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-2.1}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-1.4}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-1.05}"
    ;;
  trend_defensive)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.6}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-0.9}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.8}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-8.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.1}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.6}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-0.8}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-300}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.9}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.65}"
    ;;
  *)
    echo "unknown challenger profile: $PROFILE" >&2
    exit 2
    ;;
esac

capital_args=()
if [[ ! -f "$LOG_DIR/dry_run_state.json" ]]; then
  capital_args=(--capital "$CAPITAL")
fi

echo "Starting BTC challenger '$PROFILE' | log_dir=$LOG_DIR | config=$LIGHTER_MM_CONFIG | capital=$CAPITAL"
exec "$ROOT/venv/bin/python" -u "$ROOT/market_maker_v2.py" --symbol "$MARKET_SYMBOL" "${capital_args[@]}"
