#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <baseline_current|more_conservative|profit_tighter|trend_defensive|ultra_selective|fast_reprice_guarded|one_level_defensive|spread_quality_guarded>" >&2
  exit 2
fi

PROFILE="$1"
ROOT="${LIGHTER_MM_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
LOG_ROOT="${CHALLENGER_LOG_ROOT:-$ROOT/logs/challengers}"
LOG_DIR="${LOG_DIR:-$LOG_ROOT/$PROFILE}"
CAPITAL="${CHALLENGER_CAPITAL:-500}"

mkdir -p "$LOG_DIR"

export MARKET_SYMBOL="${MARKET_SYMBOL:-BTC}"
export LIGHTER_MM_CONFIG="${LIGHTER_MM_CONFIG:-$ROOT/configs/btc_live_100.json}"
export LOG_DIR
export RESEARCH_LOG_ENABLED="${RESEARCH_LOG_ENABLED:-true}"
export RESEARCH_LOG_ROOT_DIR="${RESEARCH_LOG_ROOT_DIR:-$LOG_DIR/research}"
export RESEARCH_LOG_RAW_RETENTION_DAYS="${RESEARCH_LOG_RAW_RETENTION_DAYS:-3}"
export RESEARCH_LOG_COMPRESSED_RETENTION_DAYS="${RESEARCH_LOG_COMPRESSED_RETENTION_DAYS:-30}"
export RESEARCH_LOG_MAX_TOTAL_MB="${RESEARCH_LOG_MAX_TOTAL_MB:-1024}"
export RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS="${RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS:-3600}"
export PYTHONUNBUFFERED=1

# Keep paper challengers gentle on the live VPS. They still use the same public
# Lighter feeds and dry-run fill simulator, but are not latency-critical.
export MIN_LOOP_INTERVAL="${MIN_LOOP_INTERVAL:-0.2}"
export SANITY_CHECK_INTERVAL="${SANITY_CHECK_INTERVAL:-30}"

case "$PROFILE" in
  baseline_current)
    # Mirrors the current live config as closely as possible.
    ;;
  more_conservative)
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.12}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.9}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-10.0}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.0}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.7}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-9.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.25}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.75}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-240}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.85}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.65}"
    ;;
  profit_tighter)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.1}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-6.0}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-30.0}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-0.55}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-2.4}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-14.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-2.1}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-1.4}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-1.05}"
    ;;
  trend_defensive)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.6}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-0.9}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.8}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-8.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.1}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.6}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-0.8}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-300}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.9}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.65}"
    ;;
  ultra_selective)
    # Tests whether fewer, wider quotes improve markout quality enough to
    # compensate for reduced fill count.  It is intentionally paper-only until
    # it proves positive spread capture and non-negative 30s markouts.
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.08}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-45.0}"
    export MIN_ORDER_LIFETIME_SECONDS="${MIN_ORDER_LIFETIME_SECONDS:-8.0}"
    export MIN_REPRICE_IMPROVEMENT_BPS="${MIN_REPRICE_IMPROVEMENT_BPS:-5.0}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-3.4}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-13.0}"
    export TOXIC_FLOW_MIN_SAMPLES="${TOXIC_FLOW_MIN_SAMPLES:-8}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.25}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.35}"
    export TOXIC_FLOW_SEVERE_ADVERSE_BPS="${TOXIC_FLOW_SEVERE_ADVERSE_BPS:-4.5}"
    export TOXIC_FLOW_INVENTORY_RATIO_TRIGGER="${TOXIC_FLOW_INVENTORY_RATIO_TRIGGER:-0.15}"
    export TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS="${TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS:-0.14}"
    export TOXIC_FLOW_MAX_SPREAD_MULTIPLIER="${TOXIC_FLOW_MAX_SPREAD_MULTIPLIER:-2.8}"
    export ADVERSE_TREND_MIN_SIDE_SAMPLES="${ADVERSE_TREND_MIN_SIDE_SAMPLES:-3}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-6.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-0.9}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.35}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-1.1}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-420}"
    export INVENTORY_EXIT_TIGHTEN_PER_RATIO="${INVENTORY_EXIT_TIGHTEN_PER_RATIO:-0.65}"
    export INVENTORY_ADD_WIDEN_PER_RATIO="${INVENTORY_ADD_WIDEN_PER_RATIO:-1.05}"
    export INVENTORY_MAX_EXIT_TIGHTEN="${INVENTORY_MAX_EXIT_TIGHTEN:-0.55}"
    export INVENTORY_MAX_ADD_WIDEN="${INVENTORY_MAX_ADD_WIDEN:-0.95}"
    export INVENTORY_ADVERSE_BOOST_PER_BPS="${INVENTORY_ADVERSE_BOOST_PER_BPS:-0.06}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.60}"
    export INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO="${INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO:-0.25}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.45}"
    export INVENTORY_DERISK_ADVERSE_TRIGGER_BPS="${INVENTORY_DERISK_ADVERSE_TRIGGER_BPS:-3.0}"
    export INVENTORY_DERISK_ADVERSE_FULL_BPS="${INVENTORY_DERISK_ADVERSE_FULL_BPS:-18.0}"
    export INVENTORY_DERISK_TIME_TO_MAX_SECONDS="${INVENTORY_DERISK_TIME_TO_MAX_SECONDS:-300.0}"
    export INVENTORY_DERISK_MAX_EXTRA_TIGHTEN="${INVENTORY_DERISK_MAX_EXTRA_TIGHTEN:-0.75}"
    export INVENTORY_DERISK_MIN_DEPTH_FACTOR="${INVENTORY_DERISK_MIN_DEPTH_FACTOR:-0.08}"
    ;;
  fast_reprice_guarded)
    # Tests whether stale quotes are the main source of adverse fills.  This
    # profile refreshes faster, but keeps wider minimum spreads and strict
    # toxicity gates so it does not simply chase every tick.
    export MIN_LOOP_INTERVAL="${FAST_REPRICE_MIN_LOOP_INTERVAL:-0.12}"
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.10}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-12.0}"
    export MIN_ORDER_LIFETIME_SECONDS="${MIN_ORDER_LIFETIME_SECONDS:-2.5}"
    export MIN_REPRICE_IMPROVEMENT_BPS="${MIN_REPRICE_IMPROVEMENT_BPS:-1.6}"
    export ORDER_TIMEOUT="${ORDER_TIMEOUT:-14.0}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.9}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-10.0}"
    export TOXIC_FLOW_MIN_SAMPLES="${TOXIC_FLOW_MIN_SAMPLES:-8}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.0}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.45}"
    export TOXIC_FLOW_SEVERE_ADVERSE_BPS="${TOXIC_FLOW_SEVERE_ADVERSE_BPS:-5.0}"
    export TOXIC_FLOW_INVENTORY_RATIO_TRIGGER="${TOXIC_FLOW_INVENTORY_RATIO_TRIGGER:-0.18}"
    export TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS="${TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS:-0.12}"
    export TOXIC_FLOW_MAX_SPREAD_MULTIPLIER="${TOXIC_FLOW_MAX_SPREAD_MULTIPLIER:-2.5}"
    export ADVERSE_TREND_MIN_SIDE_SAMPLES="${ADVERSE_TREND_MIN_SIDE_SAMPLES:-3}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-7.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.0}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.45}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-0.9}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-300}"
    export INVENTORY_EXIT_TIGHTEN_PER_RATIO="${INVENTORY_EXIT_TIGHTEN_PER_RATIO:-0.60}"
    export INVENTORY_ADD_WIDEN_PER_RATIO="${INVENTORY_ADD_WIDEN_PER_RATIO:-0.95}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.70}"
    export INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO="${INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO:-0.30}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.50}"
    export INVENTORY_DERISK_ADVERSE_TRIGGER_BPS="${INVENTORY_DERISK_ADVERSE_TRIGGER_BPS:-4.0}"
    export INVENTORY_DERISK_ADVERSE_FULL_BPS="${INVENTORY_DERISK_ADVERSE_FULL_BPS:-22.0}"
    export INVENTORY_DERISK_TIME_TO_MAX_SECONDS="${INVENTORY_DERISK_TIME_TO_MAX_SECONDS:-420.0}"
    ;;
  one_level_defensive)
    # Tests whether two quote levels are building too much inventory for a
    # small 500 USDC account.  Single-level quoting should reduce adverse
    # inventory excursions even if fill count drops.
    export LEVELS_PER_SIDE="${LEVELS_PER_SIDE:-1}"
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.11}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-28.0}"
    export MIN_ORDER_LIFETIME_SECONDS="${MIN_ORDER_LIFETIME_SECONDS:-5.0}"
    export MIN_REPRICE_IMPROVEMENT_BPS="${MIN_REPRICE_IMPROVEMENT_BPS:-3.0}"
    export ORDER_TIMEOUT="${ORDER_TIMEOUT:-24.0}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.7}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-9.5}"
    export TOXIC_FLOW_MIN_SAMPLES="${TOXIC_FLOW_MIN_SAMPLES:-8}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.0}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.5}"
    export TOXIC_FLOW_SEVERE_ADVERSE_BPS="${TOXIC_FLOW_SEVERE_ADVERSE_BPS:-5.0}"
    export TOXIC_FLOW_INVENTORY_RATIO_TRIGGER="${TOXIC_FLOW_INVENTORY_RATIO_TRIGGER:-0.18}"
    export ADVERSE_TREND_MIN_SIDE_SAMPLES="${ADVERSE_TREND_MIN_SIDE_SAMPLES:-3}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-8.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.05}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.5}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-0.9}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-360}"
    export INVENTORY_EXIT_TIGHTEN_PER_RATIO="${INVENTORY_EXIT_TIGHTEN_PER_RATIO:-0.70}"
    export INVENTORY_ADD_WIDEN_PER_RATIO="${INVENTORY_ADD_WIDEN_PER_RATIO:-1.10}"
    export INVENTORY_MAX_EXIT_TIGHTEN="${INVENTORY_MAX_EXIT_TIGHTEN:-0.60}"
    export INVENTORY_MAX_ADD_WIDEN="${INVENTORY_MAX_ADD_WIDEN:-1.00}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.55}"
    export INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO="${INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO:-0.25}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.40}"
    export INVENTORY_DERISK_ADVERSE_TRIGGER_BPS="${INVENTORY_DERISK_ADVERSE_TRIGGER_BPS:-3.5}"
    export INVENTORY_DERISK_ADVERSE_FULL_BPS="${INVENTORY_DERISK_ADVERSE_FULL_BPS:-18.0}"
    export INVENTORY_DERISK_TIME_TO_MAX_SECONDS="${INVENTORY_DERISK_TIME_TO_MAX_SECONDS:-360.0}"
    export INVENTORY_DERISK_MAX_EXTRA_TIGHTEN="${INVENTORY_DERISK_MAX_EXTRA_TIGHTEN:-0.75}"
    export INVENTORY_DERISK_MIN_DEPTH_FACTOR="${INVENTORY_DERISK_MIN_DEPTH_FACTOR:-0.08}"
    ;;
  spread_quality_guarded)
    # Tests whether BTC needs stricter spread economics rather than only lower
    # inventory.  This profile accepts fewer fills, widens quickly when markout
    # degrades, and reprices stale quotes without becoming a tick chaser.
    export MIN_LOOP_INTERVAL="${SPREAD_QUALITY_MIN_LOOP_INTERVAL:-0.15}"
    export LEVELS_PER_SIDE="${LEVELS_PER_SIDE:-1}"
    export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.07}"
    export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-9.0}"
    export MIN_ORDER_LIFETIME_SECONDS="${MIN_ORDER_LIFETIME_SECONDS:-2.0}"
    export MIN_REPRICE_IMPROVEMENT_BPS="${MIN_REPRICE_IMPROVEMENT_BPS:-1.2}"
    export ORDER_TIMEOUT="${ORDER_TIMEOUT:-12.0}"
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-3.8}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-15.0}"
    export TOXIC_FLOW_MIN_SAMPLES="${TOXIC_FLOW_MIN_SAMPLES:-6}"
    export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-1.8}"
    export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.15}"
    export TOXIC_FLOW_SEVERE_ADVERSE_BPS="${TOXIC_FLOW_SEVERE_ADVERSE_BPS:-3.5}"
    export TOXIC_FLOW_INVENTORY_RATIO_TRIGGER="${TOXIC_FLOW_INVENTORY_RATIO_TRIGGER:-0.10}"
    export TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS="${TOXIC_FLOW_SPREAD_WIDEN_PER_ADVERSE_BPS:-0.20}"
    export TOXIC_FLOW_MAX_SPREAD_MULTIPLIER="${TOXIC_FLOW_MAX_SPREAD_MULTIPLIER:-3.5}"
    export ADVERSE_TREND_MIN_SIDE_SAMPLES="${ADVERSE_TREND_MIN_SIDE_SAMPLES:-2}"
    export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-5.0}"
    export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-0.70}"
    export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.25}"
    export ADVERSE_TREND_SPREAD_FLOOR_BPS="${ADVERSE_TREND_SPREAD_FLOOR_BPS:-1.40}"
    export ADVERSE_TREND_COOLDOWN_SECONDS="${ADVERSE_TREND_COOLDOWN_SECONDS:-600}"
    export INVENTORY_EXIT_TIGHTEN_PER_RATIO="${INVENTORY_EXIT_TIGHTEN_PER_RATIO:-0.75}"
    export INVENTORY_ADD_WIDEN_PER_RATIO="${INVENTORY_ADD_WIDEN_PER_RATIO:-1.25}"
    export INVENTORY_MAX_EXIT_TIGHTEN="${INVENTORY_MAX_EXIT_TIGHTEN:-0.65}"
    export INVENTORY_MAX_ADD_WIDEN="${INVENTORY_MAX_ADD_WIDEN:-1.15}"
    export INVENTORY_ADVERSE_BOOST_PER_BPS="${INVENTORY_ADVERSE_BOOST_PER_BPS:-0.08}"
    export INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO="${INVENTORY_EXIT_HYSTERESIS_ENTER_RATIO:-0.45}"
    export INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO="${INVENTORY_EXIT_HYSTERESIS_EXIT_RATIO:-0.20}"
    export INVENTORY_DERISK_START_RATIO="${INVENTORY_DERISK_START_RATIO:-0.35}"
    export INVENTORY_DERISK_ADVERSE_TRIGGER_BPS="${INVENTORY_DERISK_ADVERSE_TRIGGER_BPS:-2.5}"
    export INVENTORY_DERISK_ADVERSE_FULL_BPS="${INVENTORY_DERISK_ADVERSE_FULL_BPS:-14.0}"
    export INVENTORY_DERISK_TIME_TO_MAX_SECONDS="${INVENTORY_DERISK_TIME_TO_MAX_SECONDS:-240.0}"
    export INVENTORY_DERISK_MAX_EXTRA_TIGHTEN="${INVENTORY_DERISK_MAX_EXTRA_TIGHTEN:-0.85}"
    export INVENTORY_DERISK_MIN_DEPTH_FACTOR="${INVENTORY_DERISK_MIN_DEPTH_FACTOR:-0.06}"
    ;;
  *)
    echo "unknown challenger profile: $PROFILE" >&2
    exit 2
    ;;
esac

capital_args=()
if [[ ! -f "$LOG_DIR/dry_run_state.json" ]]; then
  capital_args=(--capital "$CAPITAL")
fi

echo "Starting ${MARKET_SYMBOL} challenger '$PROFILE' | log_dir=$LOG_DIR | config=$LIGHTER_MM_CONFIG | capital=$CAPITAL"
exec "$ROOT/venv/bin/python" -u "$ROOT/market_maker_v2.py" --symbol "$MARKET_SYMBOL" "${capital_args[@]}"
