#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <spread_35|spread_45|spread_55|spread_65|spread_85|spread_110>" >&2
  exit 2
fi

PROFILE="$1"
ROOT="${LIGHTER_MM_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
SYMBOL="${MARKET_SYMBOL:-HYPE}"
SYMBOL_LC="$(printf "%s" "$SYMBOL" | tr '[:upper:]' '[:lower:]')"
LOG_ROOT="${CHALLENGER_LOG_ROOT:-$ROOT/logs/challengers_${SYMBOL_LC}}"
LOG_DIR="${LOG_DIR:-$LOG_ROOT/$PROFILE}"
CAPITAL="${CHALLENGER_CAPITAL:-500}"

mkdir -p "$LOG_DIR"

export MARKET_SYMBOL="$SYMBOL"
export LOG_DIR
export RESEARCH_LOG_ENABLED="${RESEARCH_LOG_ENABLED:-true}"
export RESEARCH_LOG_ROOT_DIR="${RESEARCH_LOG_ROOT_DIR:-$LOG_DIR/research}"
export RESEARCH_LOG_RAW_RETENTION_DAYS="${RESEARCH_LOG_RAW_RETENTION_DAYS:-3}"
export RESEARCH_LOG_COMPRESSED_RETENTION_DAYS="${RESEARCH_LOG_COMPRESSED_RETENTION_DAYS:-30}"
export RESEARCH_LOG_MAX_TOTAL_MB="${RESEARCH_LOG_MAX_TOTAL_MB:-1024}"
export RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS="${RESEARCH_LOG_CLEANUP_INTERVAL_SECONDS:-3600}"
export PYTHONUNBUFFERED=1

# Paper challengers should be comparable and gentle on the live VPS.
export MIN_LOOP_INTERVAL="${MIN_LOOP_INTERVAL:-0.18}"
export SANITY_CHECK_INTERVAL="${SANITY_CHECK_INTERVAL:-30}"
export LEVELS_PER_SIDE="${LEVELS_PER_SIDE:-2}"
export CAPITAL_USAGE_PERCENT="${CAPITAL_USAGE_PERCENT:-0.08}"
export DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS="${DEFAULT_QUOTE_UPDATE_THRESHOLD_BPS:-18.0}"
export MIN_ORDER_LIFETIME_SECONDS="${MIN_ORDER_LIFETIME_SECONDS:-20.0}"
export MIN_REPRICE_IMPROVEMENT_BPS="${MIN_REPRICE_IMPROVEMENT_BPS:-6.0}"
export RISK_ADD_QUOTE_UPDATE_THRESHOLD_BPS="${RISK_ADD_QUOTE_UPDATE_THRESHOLD_BPS:-105.0}"
export ORDER_TIMEOUT="${ORDER_TIMEOUT:-90.0}"
export TOXIC_FLOW_MIN_SAMPLES="${TOXIC_FLOW_MIN_SAMPLES:-10}"
export TOXIC_FLOW_ADVERSE_THRESHOLD_BPS="${TOXIC_FLOW_ADVERSE_THRESHOLD_BPS:-1.8}"
export TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS="${TOXIC_FLOW_SPREAD_CAPTURE_FLOOR_BPS:-0.8}"
export ADVERSE_TREND_MIN_SIDE_SAMPLES="${ADVERSE_TREND_MIN_SIDE_SAMPLES:-3}"
export ADVERSE_TREND_THRESHOLD_BPS="${ADVERSE_TREND_THRESHOLD_BPS:-10.0}"
export ADVERSE_TREND_SIDE_ADVERSE_BPS="${ADVERSE_TREND_SIDE_ADVERSE_BPS:-1.5}"
export ADVERSE_TREND_MARKOUT_LOSS_BPS="${ADVERSE_TREND_MARKOUT_LOSS_BPS:-0.8}"

case "$PROFILE" in
  spread_35)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-1.35}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-4.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-35.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-9.0}"
    ;;
  spread_45)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-1.6}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-5.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-45.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-10.5}"
    ;;
  spread_55)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-1.9}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-6.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-55.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-12.0}"
    ;;
  spread_65)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.25}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-7.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-65.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-14.0}"
    ;;
  spread_85)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-2.8}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-10.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-85.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-18.0}"
    ;;
  spread_110)
    export CJ_SPREAD_MULTIPLIER="${CJ_SPREAD_MULTIPLIER:-3.35}"
    export CJ_MIN_HALF_SPREAD_BPS="${CJ_MIN_HALF_SPREAD_BPS:-13.0}"
    export CJ_MAX_HALF_SPREAD_BPS="${CJ_MAX_HALF_SPREAD_BPS:-110.0}"
    export INVENTORY_PROFIT_CAPTURE_BPS="${INVENTORY_PROFIT_CAPTURE_BPS:-22.0}"
    ;;
  *)
    echo "unknown challenger profile: $PROFILE" >&2
    exit 2
    ;;
esac

capital_args=()
if [[ ! -f "$LOG_DIR/dry_run_state.json" ]]; then
  capital_args=(--capital "$CAPITAL")
fi

echo "Starting ${MARKET_SYMBOL} spread challenger '$PROFILE' | log_dir=$LOG_DIR | config=$LIGHTER_MM_CONFIG | capital=$CAPITAL"
exec "$ROOT/venv/bin/python" -u "$ROOT/market_maker_v2.py" --symbol "$MARKET_SYMBOL" "${capital_args[@]}"
